### ISSUE TITLE
AdapterTest tries to read a file from a hardcoded full path

### ISSUE THREAD

**Issue by argriffing** [danielmoney/GeLL#1]
https://github.com/danielmoney/GeLL/blob/master/test/ModelTest/AdapterTest.java#L58

**Comment by argriffing** [comment]
also this:
https://github.com/danielmoney/GeLL/blob/master/nbproject/project.properties#L48

I'm not an experienced java dev so I'm not sure which files are even meant to have been included in the git repo.

**Comment by danielmoney** [comment]
Whoops.  Thanks for pointing that out.  The first one is definitely an issue!  The Adapter stuff was one of the last bits added and after I'd moved  to a new position.  This obviously slipped through the cracks.  I'll try and get a new release sorted in the next couple of days.  As it's a test it shouldn't effect using the code.

The second one isn't a problem unless you want to load the project into netbeans and start editing it.  That said I'll try to update that as well - if I can work out how since that file is created by netbeans.

Although it's not a big task it may take a couple of days as I need to set all the Gell stuff up on my new computer and make sure it's all working correctly.  I'll update here once I have.

**Comment by argriffing** [comment]
also links to QuickStart.pdf on the C drive
https://github.com/danielmoney/GeLL/blob/master/build.xml#L84
https://github.com/danielmoney/GeLL/blob/master/build.xml#L94
https://github.com/danielmoney/GeLL/blob/master/build.xml#L106

**Comment by danielmoney** [comment]
Should all now be fixed.
